### ISSUE TITLE
Encode media previews

### ISSUE THREAD

**Issue by zkat** [digitalworkersguild/banchan#160]
Right now, we serve media previews for both images and videos as-is.

Instead, we should figure out a good scheme for encoding what we serve up when someone clicks on a media thumbnail in the commissions page.

**Comment by simplesthing** [comment]
Taking a stab at defining some file upload types and thumbnail generation, last two types could use icons instead of thumbnails

Proposal for the following image upload formats to generate `.jpeg` files

# IMAGE
  * .ai  - Adobe Illustrator files, can convert to jpg for thumbnails using ghostscript<sup>1</sup>
  * .bmp - Microsoft Windows bitmap image
  * .eps - Encapsulated PostScript, can convert to jpg for thumbnails using ghostscript<sup>1</sup>
  * .gif - CompuServe graphics interchange format, *no jpeg conversion for thumbnails
  * .HEIC - High Efficiency Image Format (1.12.0)
  * .jpg .jpeg .JPG .JPEG - Joint Photographic Experts Group JFIF format
  * .png .PNG - PNG inheriting bit-depth, color-type from original, if possible
  * .psd - Adobe Photoshop bitmap<sup>2</sup>
  * .svg - Scalable Vector Graphics (XML 2.9.4) <sup>3</sup>
  * .tiff - Tagged Image File Format
  * .webp - WebP Image Format
  * .xcf - GIMP image<sup>2</sup>

1) See [ChromicPdf](https://github.com/bitcrowd/chromic_pdf/blob/main/lib/chromic_pdf/pdfa/ghostscript_impl.ex#L78) for implementation details
2) Layered format conversion use `-0.jpeg` converted file name for thumbnails
3) Requires flatten to bg and a density to be defined in mogrify command

# VIDEO
Video files should use ffmpeg for thumbnail generation, see [ffmpex](https://github.com/talklittle/ffmpex) for elixir wrapper

  * .mov - MPEG Video Stream
  * .mp4 - VIDEO-4 Video Stream 
  * .mpeg  .mpg - MPEG Video Stream
  * .webm - Open Web Media
  * .wmv - Windows Media Video

# AUDIO
  * .mp3
  * .ogg
  * .wav

# DOCUMENTS
  * .doc
  * .doc
  * .pdf
  * .text
